trigger:
  batch: true
  branches:
    include:
      - '*'
pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: github
      name: leoviana00/azure-templates-pipeline
      ref: 'refs/heads/azuredevops/templates'
      endpoint: 'leoviana00'

variables:
  - group: acr
  - template: templates/java/ci-vars-template.yml@templates
    parameters:
      projectName: rest-calculator-java
      dockerRegistryServiceConnectionName: acr-connection-aks
      dockerfile: 'Dockerfile'
      buildContext: '$(Build.SourcesDirectory)'

steps:
  - template: templates/java/ci-steps-template.yml@templates
    displayName: ${{ parameters.projectName }} - CI - $(build.buildId)
  
 